Repository deadmade/IsoPruefi, pull requests merged in 2025-07, with the labels that each got.

#13 chore: renamed README to english
  README.md
Labels: documentation

#28 UI
  .github/workflows/docs.yml
  isopruefi-frontend/.dockerignore
  isopruefi-frontend/README.md
  isopruefi-frontend/package-lock.json
  isopruefi-frontend/package.json
  isopruefi-frontend/src/App.js
  isopruefi-frontend/src/App.test.tsx
  isopruefi-frontend/src/App.tsx
  isopruefi-frontend/src/Weather.tsx
  isopruefi-frontend/src/index.tsx
  isopruefi-frontend/src/react-app-env.d.ts
  isopruefi-frontend/src/reportWebVitals.ts
  isopruefi-frontend/src/setupTests.ts
  isopruefi-frontend/tsconfig.json
Labels: enhancement

#51 Feat/plausibility criteria for temp data
  isopruefi-backend/Database/Migrations/20250731160335_PlausibilityCheck.Designer.cs
  isopruefi-backend/Database/Migrations/20250731160335_PlausibilityCheck.cs
  isopruefi-backend/Rest-API/Controllers/GetTemperatureData.cs
  isopruefi-backend/Rest-API/Program.cs
  isopruefi-backend/Rest-API/appsettings.Development.json
Labels: enhancement, .NET
